# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/ctbs-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    #- ./:/etc/hyperledger/configtx
    - ./channel-artifacts/:/var/hyperledger/orderer/
    - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    networks:
      - byfn
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-Containeragency
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.Containeragency.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/f3eaedf05b6297d819a5bed096bd4391c2ec4700e30a3b6aa40d9977d20a7a1f_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.Containeragency.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/f3eaedf05b6297d819a5bed096bd4391c2ec4700e30a3b6aa40d9977d20a7a1f_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/Containeragency.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerContaineragency
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-Truckagency
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.Truckagency.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b9fa0d61bc316c80f979e9f9ac0c7a565bf714afae73bbe9bde7c3aa5db7fc3b_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.Truckagency.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/b9fa0d61bc316c80f979e9f9ac0c7a565bf714afae73bbe9bde7c3aa5db7fc3b_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/Truckagency.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerTruckagency
    networks:
      - byfn
  ca2:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-Rampagency
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.Rampagency.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b9c5e6ec4b54221b7f149630adc264b6604349379a87ab4113c9e82c73e58ecb_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.Rampagency.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/b9c5e6ec4b54221b7f149630adc264b6604349379a87ab4113c9e82c73e58ecb_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/Rampagency.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerRampagency
    networks:
      - byfn

  ca3:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-Customers
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.Customers.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/fc6f3a7e123cb4e49482510069dc57381e1954136f40e3d812b819b86447a312_sk
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.Customers.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/fc6f3a7e123cb4e49482510069dc57381e1954136f40e3d812b819b86447a312_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/Customers.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerCustomers
    networks:
      - byfn

  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    ports:
      - "5984:5984"
    networks:
      - byfn

  peer0.Containeragency.example.com:
    container_name: peer0.Containeragency.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.Containeragency.example.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
    networks:
      - byfn
    depends_on:
      - couchdb0

  peer0.Truckagency.example.com:
    container_name: peer0.Truckagency.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.Truckagency.example.com
    networks:
      - byfn

  peer0.Rampagency.example.com:
    container_name: peer0.Rampagency.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.Rampagency.example.com
    networks:
      - byfn

  peer0.Customers.example.com:
    container_name: peer0.Customers.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.Customers.example.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.Containeragency.example.com:7051
      - CORE_PEER_LOCALMSPID=ContaineragencyMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Containeragency.example.com/peers/peer0.Containeragency.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Containeragency.example.com/peers/peer0.Containeragency.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Containeragency.example.com/peers/peer0.Containeragency.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Containeragency.example.com/users/Admin@Containeragency.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    #command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY} ${LANG}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ././chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        #- ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.Containeragency.example.com
      - peer0.Truckagency.example.com
      - peer0.Rampagency.example.com
      - peer0.Customers.example.com
    networks:
      - byfn
